spring:
  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
        hibernate.hbm2ddl.import_files: import.sql

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:D:/db;AUTO_SERVER=TRUE
    username: sa
    password:

server:
     port: 9000

jwt:
  token:
    secret: ChangeMeToSomethingElse

logging.level.org.hibernate.SQL.: DEBUG
logging.file: myapplication.log
logging.level.org.hibernate.SQL: DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder: TRACE